spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://0.0.0.0:3306/sales?useSSL=false}
    username: ${DB_USER:user1}
    password: ${DB_PWD:password123}
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

management:
  health:
    db:
      enabled: true
